### ISSUE TITLE
log outside weather

### ISSUE THREAD

**Issue by redPanther** [ofalvai/raspi-weather#1]
Hi,
thx for that nice software! I have a suggestion.
How about storing the outside weather into sqlite db too?

**Comment by ofalvai** [comment]
Hi,

For my location, outside temperature seems to be unreliable compared to the reality, so I've never thought about doing anything with the data, plus the API calls are on the client side right now. But feel free to submit a pull request if you want to improve this.

**Comment by sproosy** [comment]
Hey ofalvai
Very nice bit of work! I currently am testing this for my RPI with 2 DHT22 sensors.  1 for inside and 1 for outside. I am not very fluent or good with coding etc but i do understand a little of it and can read/see how it works.
I have modified the logger.py and current.py scripts to get readings from BOTH my sensors (Pin 22 and 23).  This seems to be working fine and good, any chance you could advise on how to update or change the web interface to reflect this??? I have attached my scripts for reference.


 Im a n00b sorry!
Love your work and efforts! Thanks

[logger.txt](https://github.com/ofalvai/raspi-weather/files/3167702/logger.txt)
[current.txt](https://github.com/ofalvai/raspi-weather/files/3167704/current.txt)

**Comment by ofalvai** [comment]
Hi sproosy,

I'm no longer using this software myself, I switched to [Home Assistant](https://www.home-assistant.io), which works the DHT-22 sensor. I'm also running an instance of [Grafana](https://grafana.com/) to have really nice graphs. I can highly recommend both software projects, especially if you are not an experienced programmer and want to set things up without writing custom code.
